// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA76SNZ09z57mLcau1QqmrP9zS_d7_5Whc',
    appId: '1:823199012789:web:28a2b7834597d64d3cebfc',
    messagingSenderId: '823199012789',
    projectId: 'new-chatapps',
    authDomain: 'new-chatapps.firebaseapp.com',
    storageBucket: 'new-chatapps.firebasestorage.app',
    measurementId: 'G-TW2QMZD1HQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBheReXdNufARmMaIIYR-3GkbNMcS9dnRY',
    appId: '1:823199012789:ios:2f89e9bba8e38c1e3cebfc',
    messagingSenderId: '823199012789',
    projectId: 'new-chatapps',
    storageBucket: 'new-chatapps.firebasestorage.app',
    iosBundleId: 'com.example.chatApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA76SNZ09z57mLcau1QqmrP9zS_d7_5Whc',
    appId: '1:823199012789:web:4b4ff1cfe3c551423cebfc',
    messagingSenderId: '823199012789',
    projectId: 'new-chatapps',
    authDomain: 'new-chatapps.firebaseapp.com',
    storageBucket: 'new-chatapps.firebasestorage.app',
    measurementId: 'G-1MEQY834EC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBheReXdNufARmMaIIYR-3GkbNMcS9dnRY',
    appId: '1:823199012789:ios:2f89e9bba8e38c1e3cebfc',
    messagingSenderId: '823199012789',
    projectId: 'new-chatapps',
    storageBucket: 'new-chatapps.firebasestorage.app',
    iosBundleId: 'com.example.chatApps',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgbQdsxgJmB__nfMTItq2Qno9Plzn5q20',
    appId: '1:823199012789:android:e329ac7611c71cc53cebfc',
    messagingSenderId: '823199012789',
    projectId: 'new-chatapps',
    storageBucket: 'new-chatapps.firebasestorage.app',
  );

}